version: 0.2
phases:
  build:
    commands:
      - echo "Zipping deployment package..."
      - git clone https://github.com/khajum7/tdms-dev.git
      - zip -r9 deployment_package.zip tdms-dev/*sss
      idjeioene
      ok ok
  update is on
      

post_build:
  commands:

    - echo "Deploying to Lambda wasdafadsit..."
  

    - echo "Deploying to Lambda from kejghshab..."
  - echo "Deploying to Lambda from kejghshab..."
    - aws lambda update-function-code --function-name Testing-CICD --zip-file fileb://deployment_package.zip --debug



artifacts:
  files: deployment_package.zip
