version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies..








  build:
    commands:
      - echo Build started on `date`
      - echo Building the project...

  post_build:
    commands:
      - echo Creating deployment package...
      - zip -r lambda.zip .
      - echo Deploying to Lambda...
      - aws lambda update-function-code --function-name Testing-CICD --zip-file fileb://lambda.zip --region us-west-1

artifacts:
  files:
    - lambda.zip
