name: Deploy Python Lambda

on:
  push:
    branches:
      - staging  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Choose the Python version you want to use
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code --function-name Testing-CICD --zip-file fileb://path/to/your/lambda.zip --region your-region
      env:
        AWS_DEFAULT_REGION: us-west-1
